"use strict";
//They think of something you could store in a TypeScript Object. Write a program that creates Objects containing these items.
let car1 = { name: "BMW", model: 2020, colour: "Black" };
let car2 = { name: "Audi", model: 2023, colour: "Silver" };
let car3 = { name: "Peugeot", model: 2021, colour: "Purple" };
let car4 = { name: "Mercedes", model: 2022, colour: "White" };
let car5 = { name: "Jaguar", model: 2023, colour: "Blue" };
console.log("\nCar 1");
console.log("Name:", car1.name);
console.log("Model:", car1.model);
console.log("Colour:", car1.colour);
console.log("\nCar 2");
console.log("Name:", car2.name);
console.log("Model:", car2.model);
console.log("Colour:", car2.colour);
console.log("\nCar 3");
console.log("Name:", car3.name);
console.log("Model:", car3.model);
console.log("Colour:", car3.colour);
console.log("\nCar 4");
console.log("Name:", car4.name);
console.log("Model:", car4.model);
console.log("Colour:", car4.colour);
console.log("\nCar 5");
console.log("Name:", car5.name);
console.log("Model:", car5.model);
console.log("Colour:", car5.colour);
